# Generated by Django 3.2.8 on 2021-12-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0002_auto_20211202_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='loge',
            new_name='logo',
        ),
    ]
