# Generated by Django 3.2.8 on 2021-12-02 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycode', '0004_rename_userid_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='设计师',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('designstyle', models.CharField(blank=True, max_length=256)),
                ('designFeature', models.CharField(blank=True, max_length=256)),
                ('mobile', models.CharField(blank=True, max_length=256)),
                ('logo', models.URLField(blank=True, max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='建材',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('allName', models.CharField(blank=True, max_length=256)),
                ('mobile', models.CharField(blank=True, max_length=256)),
                ('logo', models.URLField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
