# Generated by Django 3.2.8 on 2021-12-02 11:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycode', '0005_建材_设计师'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='设计师',
            new_name='Designer',
        ),
        migrations.RenameModel(
            old_name='建材',
            new_name='Materials',
        ),
    ]
