# Generated by Django 3.2.8 on 2021-12-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0006_auto_20211202_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
