# Generated by Django 3.2.8 on 2021-12-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0007_designer_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designer',
            old_name='logo',
            new_name='photo',
        ),
    ]
