# Generated by Django 3.2.8 on 2021-12-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0008_rename_logo_designer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycode.city'),
        ),
        migrations.AlterField(
            model_name='designer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycode.city'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycode.city'),
        ),
    ]
