# Generated by Django 3.2.8 on 2021-12-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0009_auto_20211202_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='designer',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='materials',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
