# Generated by Django 3.2.8 on 2021-12-02 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycode', '0011_auto_20211202_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='designer',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='materials',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='designer',
            unique_together={('user', 'city')},
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
