# Generated by Django 3.2.8 on 2021-12-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0013_auto_20211202_2156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('username', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='designer',
            unique_together={('username', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='materials',
            unique_together={('username', 'city')},
        ),
    ]
